### ISSUE TITLE
hi sir...!!!

### ISSUE THREAD

**Issue by KaranjotSingh001** [rtkasodariya/Blog#3]
hello sir , your code very good i am trying to use this and also read this can you tell me when we publish a new post it will goes into the posts_buffer. please can u tell me how it will go to posts table so it will be show at home page. any user will allow that . Actually am tried from admin account also but it's not worked.

**Comment by rajan596** [comment]
@KaranjotSingh001 https://github.com/rtkasodariya/Blog/blob/master/include/accept_requested_post.php This page is transferring approved posts from posts_buffer to posts. It is working in my PC. check your sql file. And further if you are having any issue send a screen shot of error page to me. I will try to solve it.

**Comment by KaranjotSingh001** [comment]
thnks it's worked
